version: "3"
services:
  web:
    build: .
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      - BASE_URL=http://${HOST_IP}:${HOST_PORT}/
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=${CONTAINER_PORT}
      - NODE_ENV=production
